### PR TITLE
Upgraded to ES6

### PR DESCRIPTION
**Pull request by whizkydee**
Hi @ireade,

I upgraded the script to **ES6**. You might not like it anyways, feel free to close the PR.

Here are the new changes:
- Added a **.jshintrc** file.
- Added a **.gitignore** file.
- Fixed typo in **README.md**
- Created a **js/src** folder for the raw **ES6** code.
- Created a **js/dist** folder for the transpiled **ES6** code. The browser runs **ES5** code.
- On line 193 of the **js/src/script.js** file; I added an **event** parameter to the **addEventListener** function to prevent the form action.
- **Coming:** Post feedback to users in a box if the form is valid or invalid on submit (why i prevented the form action).
- **Coming:** Use Gulp Babel to automate the transpile process of the scripts.

_You might not like the ES5 output. That's the result I got when I used Babel. It's as a result of the ES6 class. You should get familiar with with the syntax of the transpiled code._

All things work fine😄😄👌.

formvalidationrealtime

### CODE REVIEW

**Comment by ireade** [comment]
Hi @whizkydee ,

First of all, really great work on this 👍🏾

However, the purpose of this repo is a demo of what I created in my video tutorial. I don't want it to become completely different to what I created there. I think you should fork the repository and keep your ES6 version there. I can link to it from the README here if you like, but I don't want to completely alter what is on this repository. 

Thanks!

**Comment by ireade** [comment]
Hi @whizkydee 

First of all, really great job on this 👍🏾

However, the purpose of this repository is to be the source for what I created in my original video tutorial. Although I've accepted minor cleanups, I don't want it to become a different thing otherwise it loses it's purpose. I think you should fork the repository and keep the ES6 version there. I can link to it from the readme if you like, but I don't want to completely alter this repository from what it was originally. 

Thanks!

**Comment by whizkydee** [comment]
Yeah @ireade,

I totally understand exactly what you are saying.
Cool, it's not for production purposes but for your tutorial and it shouldn't be different from the one in the video.
No issues. 😄😄

**Comment by ireade** [comment]
@whizkydee cool, let me know if you keep the ES6 version on your own repository

**Comment by whizkydee** [comment]
@ireade I'll keep it.

**Comment by ireade** [comment]
Ok send me the link

**Comment by whizkydee** [comment]
http://github.com/whizkydee/form-validation-realtime.
Also check [this commit](https://github.com/whizkydee/form-validation-realtime/commit/0d8b136a54df6f411e5eb7dcbbe961e2edb3304f) for a typo fix in the README

**Comment by ireade** [comment]
Great thanks, will add the link now

**Comment by whizkydee** [comment]
👍

**Comment by whizkydee** [comment]
@ireade guess you should keep up with ES6.

**Comment by ireade** [comment]
@whizkydee yes I use it in some cases, but didn't want to add the extra complication when the purpose of this was something else.

**Comment by whizkydee** [comment]
Oh, yeah. 😄

**Comment by whizkydee** [comment]
@ireade. Any conferences in Lagos?? I would like to attend some.

**Comment by ireade** [comment]
@whizkydee Checkout http://www.meetup.com/forLoop/

**Comment by whizkydee** [comment]
I know about the forLoop, any others??

**Comment by ireade** [comment]
Not that I can think of right now. If I find any I'll tweet about it so you can check there

**Comment by whizkydee** [comment]
Thanks @ireade ❤️

**Comment by ireade** [comment]
You're welcome

**Pull request closed without merging**
